const properties = [
  {
    id: 1,
    title: "3 Bedroom House For Rent in Kicukiro",
    location: "Kicukiro, Kigali",
    price: "1,435,000 RWF / month",
    type: "House",
    advertType: "Rent",
    listingType: "rent",
    bedrooms: 3,
    bathrooms: 2,
    description: "🏡 Spacious 3-bedroom house with modern amenities, 🔐 Secure parking for up to 3 cars, 🌄 Beautiful Views. 👨‍👩‍👧‍👦 Ideal for families seeking a quiet neighborhood in Kicukiro. 🍳 Joyous kitchen and 💖 lovely living room. 📶 Wifi included.",
    image : "PHOTO-2024-04-02-21-17-41 (6).jpg",
    images: [
      "PHOTO-2024-04-02-21-17-41 (6).jpg",
      "PHOTO-2024-04-02-21-17-41 (5).jpg",
      "PHOTO-2024-04-02-21-17-41 (3).jpg",
      "PHOTO-2024-04-02-21-17-41 (2).jpg"
    ],
    link: "house-details.html?id=1"
  },
  {
    id: 2,
    title: "New House For Sale in Kibagabaga with Garden",
    location: "Kibagabaga, Kigali",
    price: "330,000,000 RWF",
    type: "House",
    advertType: "Sale",
    listingType: "sale",
    bedrooms: 4,
    bathrooms: 3,
    description: "🏠 New house in Kibagabaga available for sale. 📍 Great residential location with nice views of Nyarutarama. 🛏️ Features 4 bedrooms, 🛁 3 bathrooms, 🛋️ A spacious living and dining area with natural light, 🌿 A small garden, 🧒 Kids' play area,🚗 1-car parking. 🧑‍💻 Includes a study room. 🌐 Fiber optic internet.",
    image: "KIBA new house.png",
    images: [
      "KIBA new house.png",
      "kiba house 5.png",
      "kiba house 3.png",
      "Kibagabaga New House.png",
      "kiba new house2.png",
      "kiba house 4.png"
    ],
    link: "house-details.html?id=2"
  },
  {
    id: 3,
    title: "Furnished apartment for Rent in Gishushu",
    location: "Gishushu, Kigali",
    price: "1,260,000 RWF / month",
    type: "House",
    advertType: "Rent",
    listingType: "rent",
    bedrooms: 2,
    bathrooms: 2,
    description: "Beautiful family home with spacious garden, 4 bedrooms, and 3 bathrooms. Located in the upscale neighborhood of Nyarutarama.",
    image : "gishushu 1.png",
    images: [
      "gishushu 1.png",
      "gishu 4.png",
      "gishu 5.png",
      "gishu 6.png",
      "gishu 3.png",
      "gishushu 2.png"
    ],
    link: "house-details.html?id=3"
  },
  {
    id: 4,
    title: "Spacious 5-Bedroom Home in Kibagabaga",
    location: "Kibagabaga, Kigali",
    price: "330,000,000 RWF",
    advertType: "Sale",
    listingType:"sale",
    type: "House",
    bedrooms: 5,
    bathrooms: 5,
    image:"images/sale2.png",
    images: [
      "images/sale2.png",
      "images/sale2b.png",
      "images/sale2c.png",
      "images/sale2d.png",
      "images/sale2c.png",
      "images/sale2e.png"
    ],
    description: `🏡 Spacious and beautifully finished home.  🛏️ 5 spacious bedrooms,  🚿 5 modern bathrooms,  🛋️ 2 large living rooms + dining area,  🍽️ Fully equipped indoor kitchen + outdoor kitchenette,  🧳 Store room for added storage,  🧑‍💼 Servant’s quarters in the backyard,  🚗 Parking space available,  🌿 Small private garden + backyard,  🌄 Balconies with scenic Kibagabaga views,  💧 Water tank for backup supply,  🌐 Wi-Fi ready  ,🛣️ Located on a tarmac road for easy access`,
    whatsapp: "250788123456",
    link:"house-details.html?id=4",
  },
  {
    id: 5,
    title: "Modern 4-Bedroom House in Bugesera",
    location: "Bugesera, Eastern Province",
    price: "210,000,000 RWF",
    advertType: "Sale",
    listingType: "sale",
    type: "House",
    bedrooms: 4,
    bathrooms: 3,
    image: "buga A.png",
    images: [
      "buga A.png",
      "buga B.png",
      "buga C.png",
      "buga D.png",
      "buga E.png",
      "buga F.png",
      "buga G.png",
      "buga H.png"
    ],
    description: `🏠 Discover your dream home in beautiful Bugesera, 🌅 Modern architecture blended with traditional Rwandan design, 🛋️ Spacious living areas filled with natural light, 📍 Prime location near tarmac road, close to Nyamata town, 🛏️ 4 bedrooms, 3 bathrooms, 🛋️ Cozy love seats and stylish outdoor furniture, 📺 85-inch TV + 32-inch TV included, 🛏️ Three queen-size beds with nightstands, 🪴 Indoor & outdoor plants for enhanced aesthetic, 💧 Water harvesting tank for sustainability, 🚪 Fully furnished and move-in ready`,
    whatsapp: "250788987654",
    link: "house-details.html?id=5"
  },
  {
    id: 6,
    title: "Fully Furnished 2-Bedroom Apartment in Kacyiru",
    location: "Kacyiru, Kigali",
    price: "850,000 RWF / month",
    advertType: "Rent",
    listingType: "rent",
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    image: "kac A.png",
    images: [
      "kac A.png",
      "KACU B.png",
      "KACU C.png",
      "KACU D.png",
      "KACU E.png",
      "KACU F.png"
    ],
    description: `🏢 Modern 2-bedroom apartment in Kacyiru, 🛋️ Spacious and bright living room, 🍽️ Dining area for meals and gatherings, 🛏️ 2 well-furnished bedrooms, 🚿 2 clean bathrooms with modern fittings, 🧳 Store room for extra storage, 🍳 Fully equipped indoor kitchen, 🌇 Balcony with a scenic view, 🛣️ Located on a tarmac road for easy access, 🌐 High-speed Wi-Fi access, 🌿 Small private garden, 🚗 Private parking space, ✨ Stylish and clean interiors, 🛋️ Fully furnished with all essentials, 🏘️ Quiet and friendly neighborhood`,
    whatsapp: "250788654321",
    link: "house-details.html?id=6"
  },
  {
    id: 7,
    title: "Apartment for Rent in Kimihurura Kigali",
    location: "Kimihurura, Kigali",
    price: "1,400,000 RWF / month",
    advertType: "Rent",
    listingType: "rent",
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    image: "images/KIMU A.png",
    images: [
      "images/KIMU A.png",
      "images/KIMU B.png",
      "images/KIMU C.png",
      "images/KIMU D.png",
      "images/KIMU E.png",
      "images/KIMU F.png",
      "images/KIMU G.png",
      "images/KIMU H.png"
    ],
    description: `🛏️ 2 spacious bedrooms, 🚿 2 modern bathrooms (including en-suite), 🛋️ Furnished living room with quality furniture, 🍽️ Dining area with table and chairs, 🌇 Balcony with scenic views, 🍳 Modern indoor kitchen with cabinetry and appliances, 🧳 Private store room for extra storage, ✨ Good quality interior finishings throughout`,
    whatsapp: "250788654321",
    link: "house-details.html?id=7"
  },

  {
    id: 8,
    title: "House for Sale in Nyamirambo",
    location: "Nyamirambo, Kigali",
    price: "240,000,000 RWF",
    advertType: "Sale",
    listingType: "sale",
    type: "House",
    bedrooms: 5,
    bathrooms: 5,
    image: "images/NYA A.png",
    images: [
      "images/NYA A.png",
      "images/NYA B.png",
      "images/NYA C.png",
      "images/NYA D.png",
      "images/NYA E.png",
      "images/NYA F.png",
      "images/NYA G.png",
      "images/NYA H.png",
      "images/NYA I.png",
      "images/NYA J.png"
    ],
    description: `🛏️ 5 bedrooms, 🚿 5 bathrooms, 🛋️ 2 living rooms, 🍽️ Kitchen & dining area, 🧑‍💼 Home office, 🌳 Large private garden, 🏘️ 2 annexes, 📍 Located in the heart of Nyamirambo, 👨‍👩‍👧‍👦 Ideal for large families or those needing generous space in a prime Kigali neighborhood`,
    whatsapp: "250788654321",
    link: "house-details.html?id=8"
  },

  {
    id: 9,
    title: "Rebero Kigali Big house for rent",
    location: "Rebero, Kigali",
    price: "4,200,000 RWF / month",
    advertType: "Rent",
    listingType: "rent",
    type: "House",
    bedrooms: 8,
    bathrooms: 8,
    image: "images/REB A.png",
    images: [
      "images/REB A.png",
      "images/REB B.png",
      "images/REB C.png",
      "images/REB D.png",
      "images/REB E.png",
      "images/REB F.png",
      "images/REB G.png",
      "images/REB H.png"
    ],
    description: `🏘️ 3-unit furnished property with 8 bedrooms & 8 bathrooms, 🛋️ Each unit has its own living & dining room, 🛏️ Unit 1: 2 beds, 2 baths, 🛏️ Unit 2: 4 beds, 4 baths, 🛏️ Unit 3: 2 beds, 2 baths, 🚗 Parking space available, 🌿 Small garden & backyard, 🪜 Easy access with stairs, 🌄 Rooftop with Rebero views, 🪑 Terrace/balcony with outdoor furniture, 🏥 Near schools, shops, hospitals & bus station, 🛣️ On tarmac road, 🍳 Fully equipped kitchen, 🌐 Wi-Fi available, 🧼 Washing machine, 🚰 Water tank for consistent supply, 🧑‍🦱 Maid’s quarters with small bathroom`,
    whatsapp: "250788654321",
    link: "house-details.html?id=9"
  },

  {
    id: 10,
    title: "Furnished house with pool for rent in Gacuriro",
    location: "Gacuriro, Kigali",
    price: "4,200,000 RWF / month",
    advertType: "Rent",
    listingType: "rent",
    type: "House",
    bedrooms: 5,
    bathrooms: 5,
    image: "GAC A.png",
    images: [
      "GAC A.png",
      "GAC B.png",
      "GAC C.png",
      "GAC D.png",
      "GAC E.png",
      "GAC F.png",
      "GAC G.png",
      "GAC H.png",
      "GAC J.png"
    ],
    description: `🏡 Beautifully furnished 5-bedroom home in Gacuriro, 🛏️ Each bedroom has its own bathroom, 🧑‍💼 Master bedroom includes a private office space, 🚿 5 clean and modern bathrooms, 🛋️ Elegant living and dining room setup, 🍳 Modern indoor kitchen with appliances, 🧼 Washing machine included, 🌐 High-speed Wi-Fi installed, ✨ Fully furnished with high-quality furniture and finishes, 🌄 Located near Umucyo Estate with stunning views, 🧘 Serene and peaceful environment`,
    whatsapp: "250788654321",
    link: "house-details.html?id=10"
  },

  {
    id: 11,
    title: "Top-Floor Apartment with Panoramic City Views - For Sale in Kibagabaga",
    location: "Kibagabaga, Kigali",
    price: "252,000,000 RWF",
    advertType: "Sale",
    listingType: "sale",
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    image: "KIBA A.png",
    images: [
      "KIBA A.png",
      "KIBA B.png",
      "KIBA C.png",
      "KIBA D.png",
      "KIBA E.png",
      "KIBA F.png",
      "KIBA G.png"
    ],
    description: `🛏️ 3 spacious bedrooms, 🚿 3 modern bathrooms, 🌇 Top floor with sweeping views of Kigali City Center & Nyarutarama, 🛋️ Sold fully furnished and move-in ready, 🏢 Boutique residential block of 15 units for privacy and exclusivity, ✨ Elegant modern design with natural light and premium finishes, 📍 Located in prime Kibagabaga neighborhood, 🛡️ Peaceful, secure, and convenient, 🕒 Just minutes from key amenities`,
    whatsapp: "250788654321",
    link: "house-details.html?id=11"
  },

  {
    id: 12,
    title: "Apartment for Sale in  Kanombe, Kigali",
    location: "Kanombe, Kigali",
    price: "238,000,000 RWF",
    advertType: "Sale",
    listingType: "sale",
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 2.5,
    image: "KANO A.png",
    images: [
      "KANO A.png",
      "KANO B.png",
      "KANO C.png",
      "KANO D.png",
      "KANO E.png",
      "KANO F.png",
      "KANO G.png",
      "KANO H.png"

    ],
    description: `🏢 Fully furnished income-generating apartment in Kanombe, 🛏️ 3 spacious bedrooms, 🚿 2.5 modern bathrooms, 🛋️ Bright and cozy living room, 🍽️ Elegant dining area, 🍳 Fully fitted kitchen with quality cabinetry, ✨ High-end furnishings and stylish finishings, 🌇 Private balcony with outdoor seating and Kanombe views, 🧼 Washing machine included, 🌐 Reliable Wi-Fi, 💧 Water tank for backup, 🪜 Internal stairs, 🌿 Small garden space, 💼 Ideal for homeowners or investors seeking ROI`,
    whatsapp: "250788654321",
    link: "house-details.html?id=12"
  }
  
];
