const properties = [
  {
    id: 1,
    title: "New 5 Bedroom House for Sale in Kicukiro",
    location: "Kicukiro - Kagarama, Kigali",
    price: "180,000,000 RWF",
    type: "House",
    advertType: "Sale",
    listingType: "sale",
    bedrooms: 5,
    bathrooms: 4,
    description: "🏡 Spacious 5-bedroom house in Kicukiro Kagarama. 🛁 Features 4 bathrooms for optimal comfort. 🍳 Modern inside kitchen perfect for home cooking. 🏠 Includes an annex for extra living or storage space. 🚗 Ample parking space for multiple vehicles. 🛋 Comfortable sitting room for relaxation. 🍽 Elegant dining room ideal for family meals.",
    image : "images/PHOTO-2025-08-08-14-49-55 (1).jpg",
    images: [
      "images/PHOTO-2025-08-08-14-49-55 (1).jpg",
      "images/PHOTO-2025-08-08-14-49-56 (1).jpg",
      "images/PHOTO-2025-08-08-14-49-56 (2).jpg",
      "images/PHOTO-2025-08-08-14-49-56 (3).jpg",
      "images/PHOTO-2025-08-08-14-49-56.jpg",
      "images/PHOTO-2025-08-08-14-49-57 (1).jpg",
      "images/PHOTO-2025-08-08-14-49-57 (2).jpg",
      "images/PHOTO-2025-08-08-14-49-57 (3).jpg",
      "images/PHOTO-2025-08-08-14-49-57.jpg"
    ],
    whatsapp : "250785312621",
    link: "house-details.html?id=1"
  },
  {
    id: 2,
    title: "3 Bedroom House For Rent in Kicukiro",
    location: "Kicukiro, Kigali",
    price: "1,435,000 RWF / month",
    type: "House",
    advertType: "Rent",
    listingType: "rent",
    bedrooms: 3,
    bathrooms: 2,
    description: "🏡 Spacious 3-bedroom house with modern amenities, 🔐 Secure parking for up to 3 cars, 🌄 Beautiful Views. 👨‍👩‍👧‍👦 Ideal for families seeking a quiet neighborhood in Kicukiro. 🍳 Joyous kitchen and 💖 lovely living room. 📶 Wifi included.",
    image : "images/PHOTO-2024-04-02-21-17-41 (6).jpg",
    images: [
      "images/PHOTO-2024-04-02-21-17-41 (6).jpg",
      "images/PHOTO-2024-04-02-21-17-41 (1).jpg",
      "images/PHOTO-2024-04-02-21-17-41 (3).jpg",
      "images/PHOTO-2024-04-02-21-17-41 (4).jpg",
      "images/PHOTO-2024-04-02-21-17-41 (5).jpg"
    ],
    whatsapp : "447939867796",
    link: "house-details.html?id=2"
  },
  {
    id: 3,
    title: "Modern House for Sale in Kabeza Near Kumucyo",
    location: "Kabeza, Kigali",
    price: "100,000,000 RWF",
    type: "House",
    advertType: "Sale",
    listingType: "sale",
    bedrooms: 4,
    bathrooms: 3,
    description: "🏡 Beautiful family home, 🚗 Secure Car Parking , 🛏️ 4 bedrooms, 🚿  3 bathrooms, 📍 Located near Kumucyo",
    image : "images/PHOTO-2025-08-08-23-29-19.jpg",
    images: [
      "images/PHOTO-2025-08-08-23-29-19.jpg",
      "images/PHOTO-2025-08-08-23-29-26.jpg",
      "images/PHOTO-2025-08-08-23-29-30.jpg"
    ],
    whatsapp : "250781946596",
    link: "house-details.html?id=3"
  },
  {
    id: 4,
    title: "Full Furnished House for Rent in Kibagabaga in VIP neighbourhood",
    location: "Kibagabaga, Kigali",
    price: "2,168,124 RWF / month",
    advertType: "Rent",
    listingType:"rent",
    type: "House",
    bedrooms: 4,
    bathrooms: 4,
    image:"images/PHOTO-2025-08-08-23-28-25.jpg",
    images: [
      "images/PHOTO-2025-08-08-23-28-25.jpg",
      "images/PHOTO-2025-08-08-23-28-29.jpg",
      "images/PHOTO-2025-08-08-23-28-31.jpg",
      "images/PHOTO-2025-08-08-23-28-36.jpg",
      "images/PHOTO-2025-08-08-23-28-37.jpg",
      "images/PHOTO-2025-08-08-23-28-38.jpg",
      "images/PHOTO-2025-08-08-23-28-40.jpg",
      "images/PHOTO-2025-08-08-23-28-42.jpg",
      "images/PHOTO-2025-08-08-23-28-50.jpg",
      "images/PHOTO-2025-08-08-23-28-53.jpg"

    ],
    description: `🛏️ 4 bedrooms, 🛁 4 bathrooms, ✔️ Bedrooms and wardrobes, 🚿 Bathrooms and water heater, 🛋️ Living & dining room, 🍳 Indoor modern kitchen, 🧹 Servant house, 🌳 Green garden, 🚗 Enough parking space`,
    whatsapp: "250781946596",
    link:"house-details.html?id=4",
  },
  {
    id: 5,
    title: "Spacious 4 Bedroom House for Sale in Kanombe",
    location: "Kanombe, Kigali",
    price: "85,000,000 RWF",
    advertType: "Sale",
    listingType: "sale",
    type: "House",
    bedrooms: 4,
    bathrooms: 3,
    image: "images/PHOTO-2025-08-08-23-29-39.jpg",
    images: [
      "images/PHOTO-2025-08-08-23-29-39.jpg",
      "images/PHOTO-2025-08-08-23-29-41.jpg",
      "images/PHOTO-2025-08-08-23-29-43.jpg",
      "images/PHOTO-2025-08-08-23-29-46.jpg",
      "images/PHOTO-2025-08-08-23-29-55.jpg",
      "images/PHOTO-2025-08-08-23-29-59.jpg",
      "images/PHOTO-2025-08-08-23-30-03.jpg",
      "images/PHOTO-2025-08-08-23-30-04.jpg"
    ],
    description: `🛏️ 4 spacious bedrooms, 🛁 3 modern bathrooms, 🛋️ Cozy living & dining room, 🧹 Well-maintained servant house, 🚗 Large parking space`,
    whatsapp: "250781946596",
    link: "house-details.html?id=5"
  },
  {
    id: 6,
    title: "New Big House for Sale in Kanombe Next to Nyarugunga",
    location: "Kanombe, Kigali",
    price: "140,000,000 RWF",
    advertType: "Sale",
    listingType: "sale",
    type: "House",
    bedrooms: 4,
    bathrooms: 3,
    image: "images/PHOTO-2025-08-08-23-32-04.jpg",
    images: [
      "images/PHOTO-2025-08-08-23-32-04.jpg",
      "images/PHOTO-2025-08-08-23-32-13.jpg",
      "images/PHOTO-2025-08-08-23-32-01.jpg",
      "images/PHOTO-2025-08-08-23-34-11.jpg",
      "images/PHOTO-2025-08-08-23-31-59.jpg",
      "images/PHOTO-2025-08-08-23-32-07.jpg",
      "images/PHOTO-2025-08-08-23-32-09.jpg",
      "images/PHOTO-2025-08-08-23-32-02.jpg",
      "images/PHOTO-2025-08-08-23-32-14.jpg",
      "images/PHOTO-2025-08-08-23-34-04.jpg",
      "images/PHOTO-2025-08-08-23-33-31.jpg"
    ],
    description: `🛋️ Spacious sitting room, 🍽️ Elegant dining room, 🛏️ 4 comfortable bedrooms, 🛁 3 stylish bathrooms, 🍳 Beautiful modern kitchen with store, 🧹 Outside annex with worker’s quarters, 🌳 Lovely garden, 🚗 Ample parking space, 💧 Water tank, 🧱 100% built with durable burnt bricks, 📄 Full documents available`,
    whatsapp: "250781946596",
    link: "house-details.html?id=6"
  },
  {
    id: 7,
    title: "6 Bedroom House for Sale in Gacuriro near Simba Center Supermarket",
    location: "Gacuriro, Kigali",
    price: "1,400,000 RWF / month",
    advertType: "Sale",
    listingType: "sale",
    type: "House",
    bedrooms: 6,
    bathrooms: 2,
    image: "images/stock.jpg",
    images: [
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg"
    ],
    description: `🛏️ 2 spacious bedrooms, 🚿 2 modern bathrooms (including en-suite), 🛋️ Furnished living room with quality furniture, 🍽️ Dining area with table and chairs, 🌇 Balcony with scenic views, 🍳 Modern indoor kitchen with cabinetry and appliances, 🧳 Private store room for extra storage, ✨ Good quality interior finishings throughout`,
    whatsapp: "250788654321",
    link: "house-details.html?id=7"
  },

  {
    id: 8,
    title: "House for Sale in Nyamirambo",
    location: "Nyamirambo, Kigali",
    price: "240,000,000 RWF",
    advertType: "Sale",
    listingType: "sale",
    type: "House",
    bedrooms: 5,
    bathrooms: 5,
    image: "images/stock.jpg",
    images: [
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg"
    ],
    description: `🛏️ 5 bedrooms, 🚿 5 bathrooms, 🛋️ 2 living rooms, 🍽️ Kitchen & dining area, 🧑‍💼 Home office, 🌳 Large private garden, 🏘️ 2 annexes, 📍 Located in the heart of Nyamirambo, 👨‍👩‍👧‍👦 Ideal for large families or those needing generous space in a prime Kigali neighborhood`,
    whatsapp: "250788654321",
    link: "house-details.html?id=8"
  },

  {
    id: 9,
    title: "Rebero Kigali Big house for rent",
    location: "Rebero, Kigali",
    price: "4,200,000 RWF / month",
    advertType: "Rent",
    listingType: "rent",
    type: "House",
    bedrooms: 8,
    bathrooms: 8,
    image: "images/stock.jpg",
    images: [
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg"
    ],
    description: `🏘️ 3-unit furnished property with 8 bedrooms & 8 bathrooms, 🛋️ Each unit has its own living & dining room, 🛏️ Unit 1: 2 beds, 2 baths, 🛏️ Unit 2: 4 beds, 4 baths, 🛏️ Unit 3: 2 beds, 2 baths, 🚗 Parking space available, 🌿 Small garden & backyard, 🪜 Easy access with stairs, 🌄 Rooftop with Rebero views, 🪑 Terrace/balcony with outdoor furniture, 🏥 Near schools, shops, hospitals & bus station, 🛣️ On tarmac road, 🍳 Fully equipped kitchen, 🌐 Wi-Fi available, 🧼 Washing machine, 🚰 Water tank for consistent supply, 🧑‍🦱 Maid’s quarters with small bathroom`,
    whatsapp: "250788654321",
    link: "house-details.html?id=9"
  },

  {
    id: 10,
    title: "Furnished house with pool for rent in Gacuriro",
    location: "Gacuriro, Kigali",
    price: "4,200,000 RWF / month",
    advertType: "Rent",
    listingType: "rent",
    type: "House",
    bedrooms: 5,
    bathrooms: 5,
    image: "images/stock.jpg",
    images: [
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg"
    ],
    description: `🏡 Beautifully furnished 5-bedroom home in Gacuriro, 🛏️ Each bedroom has its own bathroom, 🧑‍💼 Master bedroom includes a private office space, 🚿 5 clean and modern bathrooms, 🛋️ Elegant living and dining room setup, 🍳 Modern indoor kitchen with appliances, 🧼 Washing machine included, 🌐 High-speed Wi-Fi installed, ✨ Fully furnished with high-quality furniture and finishes, 🌄 Located near Umucyo Estate with stunning views, 🧘 Serene and peaceful environment`,
    whatsapp: "250788654321",
    link: "house-details.html?id=10"
  },

  {
    id: 11,
    title: "Top-Floor Apartment with Panoramic City Views - For Sale in Kibagabaga",
    location: "Kibagabaga, Kigali",
    price: "252,000,000 RWF",
    advertType: "Sale",
    listingType: "sale",
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    image: "images/stock.jpg",
    images: [
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg"
    ],
    description: `🛏️ 3 spacious bedrooms, 🚿 3 modern bathrooms, 🌇 Top floor with sweeping views of Kigali City Center & Nyarutarama, 🛋️ Sold fully furnished and move-in ready, 🏢 Boutique residential block of 15 units for privacy and exclusivity, ✨ Elegant modern design with natural light and premium finishes, 📍 Located in prime Kibagabaga neighborhood, 🛡️ Peaceful, secure, and convenient, 🕒 Just minutes from key amenities`,
    whatsapp: "250788654321",
    link: "house-details.html?id=11"
  },

  {
    id: 12,
    title: "Apartment for Sale in  Kanombe, Kigali",
    location: "Kanombe, Kigali",
    price: "238,000,000 RWF",
    advertType: "Sale",
    listingType: "sale",
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 2.5,
    image: "images/stock.jpg",
    images: [
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg",
      "images/stock.jpg"

    ],
    description: `🏢 Fully furnished income-generating apartment in Kanombe, 🛏️ 3 spacious bedrooms, 🚿 2.5 modern bathrooms, 🛋️ Bright and cozy living room, 🍽️ Elegant dining area, 🍳 Fully fitted kitchen with quality cabinetry, ✨ High-end furnishings and stylish finishings, 🌇 Private balcony with outdoor seating and Kanombe views, 🧼 Washing machine included, 🌐 Reliable Wi-Fi, 💧 Water tank for backup, 🪜 Internal stairs, 🌿 Small garden space, 💼 Ideal for homeowners or investors seeking ROI`,
    whatsapp: "250788654321",
    link: "house-details.html?id=12"
  }
  
];
